---

- name: Ubuntu Development Environment
  hosts: 127.0.0.1
  user: m1r1k
  sudo: yes

  vars_files:
    - vars/main.yml

  roles:
    - linux-dev
    - geerlingguy.git
    - geerlingguy.ruby
    - geerlingguy.java
    - geerlingguy.php
    - geerlingguy.composer
    - geerlingguy.drush
    - docker.ubuntu
    - mysql
    - frontend
    - dotfiles
    - browsers
    - vm
    - misc
    - fourkitchens
