---
- name: Ubuntu Development Environment
  hosts: 127.0.0.1
  user: pcoffey
  sudo: yes

  roles:
    - web
    - nodejs
    - mysql
    - php
    - dotfiles
    - browsers
    - misc
    - fourkitchens
