---
- name: Ubuntu Development Environment
  hosts: 127.0.0.1
  user: pcoffey
  sudo: yes

  vars_files:
    - group_vars/all.yml

  roles:
    - web
    - mysql
    - php
    - dotfiles
    - browsers
