---

- name: VM | Add repository
  apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian saucy contrib' state=present

- name: VM | Add key
  apt_key: url='http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc' state=present

- name: VM | Install Virtualbox
  apt: name=virtualbox state=installed force=yes

- name: VM | Check if vagrant installed
  shell: vagrant -v
  ignore_errors: true
  register: vagrant_check

- name: VM | Download vagrant
  get_url: url=https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb dest=/tmp/vagrant_1.8.1_x86_64.deb
  when: vagrant_check.stderr.find('not found') != -1

- name: VM | Install vagrant
  apt: deb=/tmp/vagrant_1.8.1_x86_64.deb
  when: vagrant_check.stderr.find('not found') != -1

