---

- name: Install nvm
  shell: >
    wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.26.1/install.sh | bash
    creates=/home/{{ ansible_ssh_user }}/.nvm/nvm.sh

- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install stable && nvm alias default stable"
    creates=/home/{{ ansible_ssh_user }}/.nvm/alias
