---

- name: PHP5 | Install php, and other needed packages.
  action: apt pkg={{ item }} state=installed
  with_items:
    - php5
    - php5-dev
    - php-pear
    - php5-intl
    - php5-ldap
    - php5-curl
    - php5-cli
    - php5-xdebug
    - php5-mysql
    - php5-json
  tags: php5
  notify: Restart apache

- name: PHP5 | Update pear channels
  tags: php5
  command: pear update-channels

- name: PHP5 | Update pear packages
  tags: php5
  command: pear upgrade-all

- name: PHP | Set pear auto-discover
  tags: php5
  command: pear config-set auto_discover 1

- name: PHP5 | Configuration /etc/php5/apache2/php.ini
  template: src=etc-php5-apache2-php.ini dest=/etc/php5/apache2/php.ini mode=0644
  notify: Restart apache
