---

- name: Wine | Add repository
  apt_repository: repo='ppa:ubuntu-wine/ppa' state=present update_cache=yes

- name: Wine | Add repository
  apt_repository: repo='ppa:atareao/telegram' state=present update_cache=yes

- name: Wine | Add repository
  apt_repository: repo='ppa:webupd8team/sublime-text-2' state=present update_cache=yes

- name: Skype | Add skype repo
  shell: add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner" && apt-get update

- name: Misc | Install apps
  apt: name={{ item }} state=latest
  with_items:
    - sni-qt:i386
    - libdbusmenu-qt2:i386
    - libqt4-dbus:i386
    - libxss1:i386
    - telegram
    - htop
    - skype
    - wget
    - vim
    - curl
    - wine
    - sshfs
    - sublime-text
    - mercurial
    - terminator
    - zsh
    - git-core

- name: Misc | Install ZSH
  shell: wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh && chsh -s `which zsh`

- name: Misc | Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

- name: Misc | Install Viber
  shell: wget -O viber64-NoobsLab.com.deb http://download.cdn.viber.com/cdn/desktop/Linux/viber.deb && dpkg -i viber64-NoobsLab.com.deb

- name: sshfs | Load sshfs to kernal
  command: modprobe fuse
